[package]
name = "sync"
version = "0.1.0"
authors = ["The ChromiumOS Authors"]
edition = "2021"
include = ["src/**/*", "Cargo.toml"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
